
CREATE TABLE public.categories (
  category_id integer NOT NULL DEFAULT nextval('categories_category_id_seq'::regclass),
  category_name character varying NOT NULL,
  category_slug character varying NOT NULL UNIQUE,
  parent_category_id integer,
  description text,
  image_url character varying,
  icon_name character varying,
  display_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT categories_pkey PRIMARY KEY (category_id),
  CONSTRAINT categories_parent_category_id_fkey FOREIGN KEY (parent_category_id) REFERENCES public.categories(category_id)
);
CREATE TABLE public.contact_messages (
  id integer NOT NULL DEFAULT nextval('contact_messages_id_seq'::regclass),
  name character varying NOT NULL,
  email character varying NOT NULL,
  phone character varying,
  subject character varying,
  message text NOT NULL,
  status character varying DEFAULT 'pending'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT contact_messages_pkey PRIMARY KEY (id)
);
CREATE TABLE public.coupons (
  coupon_id integer NOT NULL DEFAULT nextval('coupons_coupon_id_seq'::regclass),
  coupon_code character varying NOT NULL UNIQUE,
  coupon_type character varying NOT NULL,
  discount_value numeric NOT NULL,
  min_order_amount numeric,
  max_discount_amount numeric,
  usage_limit integer,
  used_count integer DEFAULT 0,
  valid_from timestamp without time zone NOT NULL,
  valid_to timestamp without time zone NOT NULL,
  is_active boolean DEFAULT true,
  description text,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT coupons_pkey PRIMARY KEY (coupon_id)
);
CREATE TABLE public.custom_designs (
  design_id integer NOT NULL DEFAULT nextval('custom_designs_design_id_seq'::regclass),
  user_id uuid,
  guest_email character varying,
  guest_name character varying,
  guest_phone character varying,
  template_id integer,
  phone_model character varying NOT NULL,
  design_data jsonb NOT NULL,
  preview_image_url text,
  high_res_image_url text,
  status character varying DEFAULT 'draft'::character varying CHECK (status::text = ANY (ARRAY['draft'::character varying, 'submitted'::character varying, 'processing'::character varying, 'approved'::character varying, 'rejected'::character varying, 'printed'::character varying]::text[])),
  admin_notes text,
  order_id integer,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  submitted_at timestamp without time zone,
  processed_at timestamp without time zone,
  CONSTRAINT custom_designs_pkey PRIMARY KEY (design_id),
  CONSTRAINT custom_designs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT custom_designs_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.phone_templates(template_id),
  CONSTRAINT custom_designs_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(order_id)
);
CREATE TABLE public.design_collections (
  collection_id integer NOT NULL DEFAULT nextval('design_collections_collection_id_seq'::regclass),
  collection_name character varying NOT NULL,
  collection_slug character varying NOT NULL UNIQUE,
  description text,
  banner_image character varying,
  thumbnail_image character varying,
  theme_color character varying,
  is_featured boolean DEFAULT false,
  is_active boolean DEFAULT true,
  display_order integer DEFAULT 0,
  valid_from timestamp without time zone,
  valid_to timestamp without time zone,
  view_count integer DEFAULT 0,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT design_collections_pkey PRIMARY KEY (collection_id)
);
CREATE TABLE public.design_images (
  image_id integer NOT NULL DEFAULT nextval('design_images_image_id_seq'::regclass),
  design_id integer,
  original_url text NOT NULL,
  thumbnail_url text,
  file_name character varying,
  file_size integer,
  width integer,
  height integer,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT design_images_pkey PRIMARY KEY (image_id),
  CONSTRAINT design_images_design_id_fkey FOREIGN KEY (design_id) REFERENCES public.custom_designs(design_id)
);
CREATE TABLE public.gift_emails (
  email_id uuid NOT NULL DEFAULT gen_random_uuid(),
  gift_id uuid,
  email_type character varying NOT NULL,
  sent_to character varying NOT NULL,
  sent_at timestamp with time zone DEFAULT now(),
  status character varying DEFAULT 'sent'::character varying,
  CONSTRAINT gift_emails_pkey PRIMARY KEY (email_id),
  CONSTRAINT gift_emails_gift_id_fkey FOREIGN KEY (gift_id) REFERENCES public.gifts(gift_id)
);
CREATE TABLE public.gifts (
  gift_id uuid NOT NULL DEFAULT gen_random_uuid(),
  sender_id uuid,
  sender_name character varying NOT NULL,
  sender_email character varying NOT NULL,
  sender_message text,
  recipient_name character varying NOT NULL,
  recipient_email character varying NOT NULL,
  recipient_phone character varying,
  recipient_address text,
  product_id integer NOT NULL,
  quantity integer DEFAULT 1,
  verification_code character varying NOT NULL,
  status character varying DEFAULT 'pending'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  verified_at timestamp with time zone,
  claimed_at timestamp with time zone,
  expires_at timestamp with time zone DEFAULT (now() + '7 days'::interval),
  notes text,
  CONSTRAINT gifts_pkey PRIMARY KEY (gift_id),
  CONSTRAINT gifts_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES public.users(id),
  CONSTRAINT gifts_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(product_id)
);
CREATE TABLE public.inventory (
  inventory_id integer NOT NULL DEFAULT nextval('inventory_inventory_id_seq'::regclass),
  product_id integer,
  variant_id integer,
  warehouse_location character varying,
  quantity_available integer DEFAULT 0,
  quantity_reserved integer DEFAULT 0,
  quantity_sold integer DEFAULT 0,
  reorder_level integer DEFAULT 10,
  reorder_quantity integer DEFAULT 50,
  last_restock_date timestamp without time zone,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT inventory_pkey PRIMARY KEY (inventory_id),
  CONSTRAINT inventory_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(product_id),
  CONSTRAINT inventory_variant_id_fkey FOREIGN KEY (variant_id) REFERENCES public.product_variants(variant_id)
);
CREATE TABLE public.messenger_orders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  facebook_user_id character varying NOT NULL,
  customer_name character varying NOT NULL,
  phone character varying NOT NULL,
  address text NOT NULL,
  product_name character varying NOT NULL,
  product_price numeric NOT NULL DEFAULT 0,
  quantity integer NOT NULL DEFAULT 1,
  color character varying,
  total_price numeric NOT NULL DEFAULT 0,
  notes text,
  status character varying NOT NULL DEFAULT 'pending'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT messenger_orders_pkey PRIMARY KEY (id)
);
CREATE TABLE public.order_items (
  order_item_id integer NOT NULL DEFAULT nextval('order_items_order_item_id_seq'::regclass),
  order_id integer,
  product_id integer,
  variant_id integer,
  product_name character varying NOT NULL,
  variant_name character varying,
  sku character varying NOT NULL,
  quantity integer NOT NULL,
  unit_price numeric NOT NULL,
  discount_amount numeric DEFAULT 0,
  total_price numeric NOT NULL,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  phone_model_id integer,
  phone_model_name character varying,
  CONSTRAINT order_items_pkey PRIMARY KEY (order_item_id),
  CONSTRAINT order_items_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(order_id),
  CONSTRAINT order_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(product_id)
);
CREATE TABLE public.orders (
  order_id integer NOT NULL DEFAULT nextval('orders_order_id_seq'::regclass),
  order_number character varying NOT NULL UNIQUE,
  order_status character varying DEFAULT 'pending'::character varying,
  payment_status character varying DEFAULT 'unpaid'::character varying,
  payment_method character varying,
  shipping_method character varying,
  subtotal numeric NOT NULL,
  discount_amount numeric DEFAULT 0,
  shipping_fee numeric DEFAULT 0,
  tax_amount numeric DEFAULT 0,
  total_amount numeric NOT NULL,
  coupon_code character varying,
  shipping_address_id integer,
  billing_address_id integer,
  customer_note text,
  admin_note text,
  tracking_number character varying,
  shipped_at timestamp without time zone,
  delivered_at timestamp without time zone,
  cancelled_at timestamp without time zone,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  shipping_full_name character varying,
  shipping_phone character varying,
  shipping_address text,
  shipping_ward character varying,
  shipping_district character varying,
  shipping_city character varying,
  customer_id uuid,
  CONSTRAINT orders_pkey PRIMARY KEY (order_id),
  CONSTRAINT orders_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.users(id)
);
CREATE TABLE public.phone_models (
  model_id integer NOT NULL DEFAULT nextval('phone_models_model_id_seq'::regclass),
  brand_name character varying NOT NULL,
  model_name character varying NOT NULL,
  model_code character varying,
  release_year integer,
  screen_size numeric,
  dimensions character varying,
  weight character varying,
  image_url character varying,
  is_popular boolean DEFAULT false,
  is_active boolean DEFAULT true,
  display_order integer DEFAULT 0,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT phone_models_pkey PRIMARY KEY (model_id)
);
CREATE TABLE public.phone_templates (
  template_id integer NOT NULL DEFAULT nextval('phone_templates_template_id_seq'::regclass),
  phone_model character varying NOT NULL,
  brand character varying NOT NULL,
  template_image_url text,
  print_width_mm numeric DEFAULT 70,
  print_height_mm numeric DEFAULT 150,
  canvas_width integer DEFAULT 700,
  canvas_height integer DEFAULT 1500,
  is_active boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT phone_templates_pkey PRIMARY KEY (template_id)
);
CREATE TABLE public.product_collections (
  id integer NOT NULL DEFAULT nextval('product_collections_id_seq'::regclass),
  product_id integer,
  collection_id integer,
  display_order integer DEFAULT 0,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT product_collections_pkey PRIMARY KEY (id),
  CONSTRAINT product_collections_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(product_id),
  CONSTRAINT product_collections_collection_id_fkey FOREIGN KEY (collection_id) REFERENCES public.design_collections(collection_id)
);
CREATE TABLE public.product_compatibility (
  compatibility_id integer NOT NULL DEFAULT nextval('product_compatibility_compatibility_id_seq'::regclass),
  product_id integer,
  phone_model_id integer,
  fit_type character varying DEFAULT 'exact'::character varying,
  notes text,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT product_compatibility_pkey PRIMARY KEY (compatibility_id),
  CONSTRAINT product_compatibility_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(product_id),
  CONSTRAINT product_compatibility_phone_model_id_fkey FOREIGN KEY (phone_model_id) REFERENCES public.phone_models(model_id)
);
CREATE TABLE public.product_images (
  image_id integer NOT NULL DEFAULT nextval('product_images_image_id_seq'::regclass),
  product_id integer,
  variant_id integer,
  image_url character varying NOT NULL,
  alt_text character varying,
  display_order integer DEFAULT 0,
  is_primary boolean DEFAULT false,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT product_images_pkey PRIMARY KEY (image_id),
  CONSTRAINT product_images_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(product_id),
  CONSTRAINT product_images_variant_id_fkey FOREIGN KEY (variant_id) REFERENCES public.product_variants(variant_id)
);
CREATE TABLE public.product_reviews (
  review_id integer NOT NULL DEFAULT nextval('product_reviews_review_id_seq'::regclass),
  product_id integer,
  customer_id integer,
  order_id integer,
  rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
  title character varying,
  comment text,
  is_verified_purchase boolean DEFAULT false,
  is_approved boolean DEFAULT false,
  helpful_count integer DEFAULT 0,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT product_reviews_pkey PRIMARY KEY (review_id),
  CONSTRAINT product_reviews_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(product_id),
  CONSTRAINT product_reviews_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(order_id)
);
CREATE TABLE public.product_variants (
  variant_id integer NOT NULL DEFAULT nextval('product_variants_variant_id_seq'::regclass),
  product_id integer,
  sku character varying NOT NULL UNIQUE,
  variant_name character varying,
  color character varying,
  color_code character varying,
  size character varying,
  material character varying,
  price numeric,
  sale_price numeric,
  image_url character varying,
  is_active boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT product_variants_pkey PRIMARY KEY (variant_id),
  CONSTRAINT product_variants_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(product_id)
);
CREATE TABLE public.products (
  product_id integer NOT NULL DEFAULT nextval('products_product_id_seq'::regclass),
  product_name character varying NOT NULL,
  product_slug character varying NOT NULL UNIQUE,
  category_id integer,
  brand_id integer,
  sku character varying NOT NULL UNIQUE,
  description text,
  short_description text,
  price numeric NOT NULL,
  sale_price numeric,
  cost_price numeric,
  is_featured boolean DEFAULT false,
  is_new boolean DEFAULT false,
  is_bestseller boolean DEFAULT false,
  is_trending boolean DEFAULT false,
  status character varying DEFAULT 'active'::character varying,
  meta_title character varying,
  meta_description text,
  meta_keywords text,
  view_count integer DEFAULT 0,
  rating_average numeric DEFAULT 0,
  review_count integer DEFAULT 0,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  image_url text,
  season text,
  CONSTRAINT products_pkey PRIMARY KEY (product_id),
  CONSTRAINT products_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.categories(category_id)
);
CREATE TABLE public.shopping_carts (
  cart_id integer NOT NULL DEFAULT nextval('shopping_carts_cart_id_seq'::regclass),
  customer_id uuid,
  product_id integer,
  variant_id integer,
  quantity integer NOT NULL DEFAULT 1,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  phone_model_id integer,
  phone_model_name character varying,
  CONSTRAINT shopping_carts_pkey PRIMARY KEY (cart_id),
  CONSTRAINT shopping_carts_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(product_id),
  CONSTRAINT shopping_carts_variant_id_fkey FOREIGN KEY (variant_id) REFERENCES public.product_variants(variant_id),
  CONSTRAINT shopping_carts_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.users(id)
);
CREATE TABLE public.staff (
  staff_id integer NOT NULL DEFAULT nextval('staff_staff_id_seq'::regclass),
  email character varying NOT NULL UNIQUE,
  password_hash character varying NOT NULL,
  full_name character varying NOT NULL,
  phone character varying,
  role character varying NOT NULL,
  permissions text,
  is_active boolean DEFAULT true,
  last_login timestamp without time zone,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT staff_pkey PRIMARY KEY (staff_id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  email character varying NOT NULL UNIQUE,
  password_hash text NOT NULL,
  full_name character varying,
  phone character varying,
  avatar_url text,
  address text,
  is_admin boolean DEFAULT false,
  role character varying DEFAULT 'user'::character varying,
  status character varying DEFAULT 'active'::character varying,
  email_verified boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  last_login_at timestamp with time zone,
  CONSTRAINT users_pkey PRIMARY KEY (id)
);
CREATE TABLE public.wishlists (
  wishlist_id integer NOT NULL DEFAULT nextval('wishlists_wishlist_id_seq'::regclass),
  customer_id integer,
  product_id integer,
  variant_id integer,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  user_id uuid,
  CONSTRAINT wishlists_pkey PRIMARY KEY (wishlist_id),
  CONSTRAINT wishlists_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(product_id),
  CONSTRAINT wishlists_variant_id_fkey FOREIGN KEY (variant_id) REFERENCES public.product_variants(variant_id),
  CONSTRAINT wishlists_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);